FROM mongo
#ENV MONGO_INITDB_ROOT_USERNAME=admin
#ENV MONGO_INITDB_ROOT_PASSWORD=admin
#ENV MONGO_INITDB_DATABASE=test
COPY ./data/restaurant.json /init.json
#COPY ./script.sh /docker-entrypoint-initdb.d/
#COPY ./mongo-init.js /docker-entrypoint-initdb.d/



