version: '3.7'

services:
    mongodb:
        image: vicontainers/mongowithdata:latest
        build:
            context: . 
            dockerfile: Dockerfile.MongoWithData
        container_name: mongodb
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=test
        ports:
            - 27017:27017
        volumes:
            -  mongodatax:/data/db
            - ./init-scripts:/docker-entrypoint-initdb.d/:ro
        networks:
            - mongodbnt
    frontend:
        image: vicontainers/appy:1.0.0
        build:
            context: . 
            dockerfile: Dockerfile.Frontend        
        networks:
            - mongodbnt
        depends_on:
            - mongodb
        ports:
            - 8080:8080
        environment:
            - MONGO_URI=mongodb://myuser:1234@mongodb:27017/test
networks:
       mongodbnt:
volumes:
  mongodatax:
